// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqdzPfUC3i-UA6eKJ97whNyXADNrmnk_4',
    appId: '1:694922258443:web:902c20974b9f796f42bf0e',
    messagingSenderId: '694922258443',
    projectId: 'shams-522f7',
    authDomain: 'shams-522f7.firebaseapp.com',
    storageBucket: 'shams-522f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAMdm8W9QOzA7-btGlINFkxK6ZfZGAPDg',
    appId: '1:694922258443:android:b4ff2e386206c5fb42bf0e',
    messagingSenderId: '694922258443',
    projectId: 'shams-522f7',
    storageBucket: 'shams-522f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC24wGegE99AMu8qSEO2BsX03Ki9MFzE04',
    appId: '1:694922258443:ios:8024959fc7465eb942bf0e',
    messagingSenderId: '694922258443',
    projectId: 'shams-522f7',
    storageBucket: 'shams-522f7.firebasestorage.app',
    iosBundleId: 'com.example.amrshams',
  );
}
